version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run test:ci
  node9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run test:ci
workflows:
  version: 2
  test:
    jobs:
      - node8
      - node9
