version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run test:ci
workflows:
  version: 2
  test:
    jobs:
      - test
